Integración de api de Weets
wolox-training/dmq-express-js pull request #5
Opened 2021-06-03 14:42 UTC by minotad

## Summary

Connection to an external geek-joke-api api is made.

## Known Issues

None

## Trello Card

https://trello.com/c/xdL5bamg/32-servicios-promises-witter

2021-06-03 17:13 UTC, marioportela1993 requested changes
Nice code! only few comments, please check and let me know if you have questions

2021-06-03 17:13 UTC, marioportela1993 commented on WTraining/app/services/weet.js
> +const axios = require('axios');
We can to create a request helper to do requests external apis in order to wrap the axios package to be used to any service.

2021-06-03 17:13 UTC, marioportela1993 commented on WTraining/app/services/weet.js
> +    .get('https://geek-jokes.sameerkumar.website/api?format=json')
Please set this URL as env variable :)

2021-06-03 17:13 UTC, marioportela1993 commented on WTraining/app/services/weet.js
> +    .catch(e => logger.error(e));
Please throw and error to be catched in the controller

2021-06-03 22:20 UTC, marioportela1993 requested changes

2021-06-03 22:20 UTC, marioportela1993 commented on WTraining/app/services/weet.js
> +const URL = process.env.ULR_WEET;
Add this variable (ULR_WEET) in config/index.js file and retrieve the value from there

2021-06-04 13:59 UTC, emeneses4 requested changes

2021-06-04 13:59 UTC, emeneses4 commented on WTraining/app/services/weet.js
> +      throw e;
You could to throw a specific error using the Wolox error definition. I think that You should created a error in `app/errors.js `and then to define code status error in `app/middleware/errors.js ` for example 

`errors.js `
` exports.VALIDATION_ERROR = 'validation_error';
  exports.validationError = message => internalError(message, exports.VALIDATION_ERROR);
`

`middleware/errors.js
`
`
const statusCodes = {
  [errors.VALIDATION_ERROR]: 422
};
`

2021-06-04 14:50 UTC, marioportela1993 requested changes

2021-06-04 14:50 UTC, marioportela1993 commented on WTraining/config/index.js
> +    url: {
Please be more specific with the naming of variables. Here maybe is better: 

```
weetService: {
     url: process.env.ULR_WEET
}

2021-06-09 16:47 UTC, marioportela1993 approved these changes

2021-06-09 17:48 UTC, emeneses4 approved these changes

2021-06-09 20:46 UTC, merged